# Welcome to Jekyll!      
# If you change this file, restart the server: `jekyll serve -l -H localhost`
 
# Basic Site Settings  
locale         : "en-US"
site_theme     : "default"   # options: "default", "air"
title          : "Sveva Manfredi"
title_separator: "-"
name           : &name "Sveva Manfredi" 
description    : &description "Personal website of Sveva Manfredi"
url            : https://svemanfre.github.io    # user site: no baseurl
baseurl        : ""                              # keep empty for user/organization sites
repository     : "svemanfre/svemanfre.github.io" # owner/repo
logo           : "/images/apple-touch-icon.png"

# Site Author (shown in the sidebar) 
author:
  # Bio
  avatar    : "profile.png"            # put your image in /images or root as used by the theme
  name      : "Sveva Manfredi"
  pronouns  :                           # e.g., "she/her"
  bio       : "PhD student at UCLA"
  location  : "Los Angeles, CA"
  employer  : "University of California, Los Angeles"
  uri       :                           # personal homepage if different from this site
  email     :  "svemanfre@ucla.edu"

  # Academic websites
  academia      :
  arxiv         :
  googlescholar :                       # e.g., "https://scholar.google.com/citations?user=XXXXXXXXXXX"
  inspire-hep   :
  impactstory   :
  orcid         :                       # e.g., "https://orcid.org/0000-0000-0000-0000"
  semantic      :
  pubmed        :
  researchgate  :
  scopus        :

  # Repositories and software
  bitbucket     :
  codepen       :
  dribbble      :
  github        :
  kaggle        :
  stackoverflow :

  # Social media
  artstation    :
  bluesky       :                       # e.g., "yourname.bsky.social"
  facebook      :
  flickr        :
  foursquare    :
  goodreads     :
  google_plus   :
  keybase       :
  instagram     :
  lastfm        :
  linkedin      : "sveva-manfredi-38160b182"
  mastodon      :                       # e.g., "https://mastodon.social/@yourhandle"
  medium        :
  pinterest     :
  soundcloud    :
  steam         :
  telegram      :
  tumblr        :
  twitter       : "svevam3" 
  vine          :
  weibo         :
  wikipedia     :
  xing          :
  youtube       :
  zhihu         :

# Publication Category Headings
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'
  conferences:
    title: 'Conference Papers'

# Site Settings
teaser              :
breadcrumbs         : false
words_per_minute    : 160
future              : true
read_more           : "disabled"
talkmap_link        : false
comments:
  provider          : # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "custom"
  disqus:
    shortname       :
  discourse:
    server          :
  facebook:
    appid           :
    num_posts       :
    colorscheme     :
staticman:
  allowedFields     : ['name', 'email', 'url', 'message']
  branch            : "gh-pages"
  commitMessage     : "New comment."
  filename          : comment-{@timestamp}
  format            : "yml"
  moderation        : true
  path              : "_data/comments/{options.slug}"
  requiredFields    : ['name', 'email', 'message']
  transforms:
    email           : "md5"
  generatedFields:
    date:
      type          : "date"
      options:
        format      : "iso8601"
atom_feed:
  hide              : false
  path              :

# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social Sharing
twitter:
  username          : &twitter
facebook:
  username          :
  app_id            :
  publisher         :
og_image            :    # default social image path
og_description      :    # default social description
social:
  type              : Person
  name              : "Sveva Manfredi"
  links             : [] # e.g., ["https://github.com/svemanfre", "https://orcid.org/..."]

# Analytics
analytics:
  provider          : "false" # "false", "google", "google-universal", "google-analytics-4", "custom"
  google:
    tracking_id     :

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding    : "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown          : kramdown
highlighter       : rouge
lsi               : false
excerpt_separator : "\n\n"
incremental       : false

# Markdown Processing
kramdown:
  input           : GFM
  hard_wrap       : false
  auto_ids        : true
  footnote_nr     : 1
  entity_output   : as_char
  toc_levels      : 1..6
  smart_quotes    : lsquo,rsquo,ldquo,rdquo
  enable_coderay  : false

# Collections
collections:
  teaching:
    output   : true
    permalink: /:collection/:path/
  publications:
    output   : true
    permalink: /:collection/:path/
  portfolio:
    output   : true
    permalink: /:collection/:path/
  talks:
    output   : true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout        : single
      author_profile: true
      read_time     : true
      comments      : true
      share         : true
      related       : true
  - scope:
      path: ""
      type: pages
    values:
      layout        : single
      author_profile: true
  - scope:
      path: ""
      type: teaching
    values:
      layout        : single
      author_profile: true
      share         : true
      comments      : true
  - scope:
      path: ""
      type: publications
    values:
      layout        : single
      author_profile: true
      share         : true
      comments      : true
  - scope:
      path: ""
      type: portfolio
    values:
      layout        : single
      author_profile: true
      share         : true
      comment       : true
  - scope:
      path: ""
      type: talks
    values:
      layout        : talk
      author_profile: true
      share         : true

# Sass/SCSS
sass:
  sass_dir: _sass
  style   : compressed

# Outputting
permalink: /:categories/:title/
# paginate: 5
# paginate_path: /page:num/
timezone: Europe/Rome

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Mimic GitHub Pages with --safe
whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
